version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
